<h2>Přidat chladnou zbraň</h2>

<form method="POST" enctype="multipart/form-data" class="form">
    <label for="name">Název zbraně</label>
    <input type="text" name="name" id="name" required>
    <label for="material">Materiál</label>
    <input type="text" name="material" id="material" required>
    <label for="descript">Popis</label>
    <textarea name="descript" id="descript" cols="30" rows="10" placeholder="Zde zadejte popis" required></textarea>
    <label for="picture">Obrázek</label>
    <input type="file" name="picture" id="picture" accept="image/*" required>
    <button name="sendButtonColdWeapon">Přidat</button>
</form>