<h1><strong>HLAVNÍ STRÁNKA</strong></h1>
<h3><strong>VÍTEJTE NA MÉ STRÁNCE O VŠELIJAKÝCH ZBRANÍCH!</strong></h3>
<p>Na této stránce si můžete prohlédnout tabulky zbraní na blízku i na dálku, zobrazit si různé informace, nebo třeba si lze přidat zbraně do oblíbených, <br>jestliže jste zaregistrovaní a přihlášení + mnoho dalšího!</p>
<p>Admini mají navíc možnost odstranit či upravit zbraň.</p>
<p>Enjoy!</p>
<br>
<img class="rick" src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExdXYwMGpweTl4N2ZmMG8zcWs5cGhjN2t1cjl4MTQ5cDlva3duZDB3YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKqtGkUW07hDK9y/giphy.gif" alt="Rick Grimes with Revolver" width="250px">