<h1>Přihlášení</h1>

<form method="POST" enctype="multipart/form-data" class="form">
    <div>
        <label for="username">Uživatelské jméno</label>
        <input type="text" name="username" id="username" required>
    </div>
    <div>
        <label for="password">Heslo</label>
        <input type="password" name="password" id="password" required>
        <br>
    </div>
    <button name="loginForm">Přihlásit se</button>
</form>