<h1>Seznam střelných zbraní</h1>
 
<?php if (isset($_SESSION["loggedUser"]) && ($_SESSION["loggedUser"]["isadmin"] ?? 0)) { ?>
    <button class="button">
        <a href="./addhotweapon.php" class="add">Přidat střelnou zbraň<br></a>
    </button>
    <br><br>
<?php } ?>

<table border="2">
    <thead>
        <th>ID</th>
        <th>Název</th>
        <th>Ráže</th>
        <th>Úsťová rychlost v m/s</th>
        <th>Obrázek</th>
        <?php if (isset($_SESSION["loggedUser"])) { ?>
        <th>Podrobnosti</th>
        <?php } ?>
        <?php if (isset($_SESSION["loggedUser"]) && ($_SESSION["loggedUser"]["isadmin"] ?? 0)) { ?>
        <th>Upravit</th>
        <th>Odstranit</th>
        <?php } ?>
        <?php if (isset($_SESSION["loggedUser"])) { ?>
        <th>Oblíbená?</th>
        <?php } ?>
    </thead>
    <tbody>
        <?php 
            foreach ($guns as $gun) {
        ?>
            <tr>
                <td><?= $gun["id"] ?></td>
                <td><?= $gun["name"] ?></td>
                <td><?= $gun["caliber"] ?></td>
                <td><?= $gun["rang"] ?></td>
                <td>
                    <?php if (isset($gun["picture"]) && !empty($gun["picture"])) { ?>
                        <img src="<?= $gun["picture"] ?>" alt="Obrázek" height="100px">
                    <?php } else { ?>
                        Chyba!
                    <?php } ?>
                </td>
                <?php if (isset($_SESSION["loggedUser"])) { ?>
                <td>
                    <a href="hotweapon_detail.php?id=<?= $gun['id'] ?>"class="buttonshow">Zobrazit</a>
                </td>
                <?php } ?>
                <?php if (isset($_SESSION["loggedUser"]) && ($_SESSION["loggedUser"]["isadmin"] ?? 0)) { ?>
                <td>
                    <form method="GET">
                        <input type="hidden" name="edit" value="<?=$gun["id"]?>">
                        <button class="button">Upravit</button>
                    </form>
                </td>
                <td>
                    <form method="POST"> 
                        <input type="hidden" name="id" value="<?=$gun["id"]?>">   
                        <button name="deleteGun" class="button">Odstranit</button>
                    </form>    
                </td>
                <?php } ?>
                <?php if (isset($_SESSION["loggedUser"])) { ?>
                <td>
                    <form method="POST" action="./add_favorite.php" style="display:inline;">
                        <input type="hidden" name="weapon_name" value="<?= htmlspecialchars($gun['name']) ?>">
                        <input type="hidden" name="weapon_type" value="hot">
                        <button type="submit" class="buttonshow">
                            ❤ Oblíbené
                        </button>
                    </form>
                </td>
                <?php } ?>
            </tr>
        <?php
            }
        ?>
    </tbody>
</table>