<h1>Registrace</h1>

<form method="POST" enctype="multipart/form-data" class="form">
    <div>
        <label for="username">Uživatelské jméno</label>
        <input type="text" name="username" id="username" required>
    </div>
    <div>
        <label for="email">E-mail</label>
        <input type="email" name="email" id="email" required>
    </div>
    <div>
        <label for="password">Heslo</label>
        <input type="password" name="password" id="password" required>
    </div>
    <div>
        <label for="passwordConfirm">Heslo znovu</label>
        <input type="password" name="passwordConfirm" id="passwordConfirm" required>
    </div>
    <button name="registerForm">Registrovat se</button>
</form>